#!/bin/bash -e
#
# mks3upload
#
# Create a template archive suitable for uploading to S3 for use in Simulator device builds
#

AS2BACKUP=$(mktemp)
ASSETS2="$(pwd)/../test/assets2"

if [ -d $ASSETS2 ]
then
	rm $AS2BACKUP
	mv $ASSETS2 $AS2BACKUP
fi

if [ "$1" == "--clean" ] || [ "$1" == "-c" ]
then
	./build_template.sh basic release clean generic
	shift

	if [ "$1" == "--upload" ] || [ "$1" == "-u" ]
	then
		# if asked to clean then upload, be sure to build
		./build_template.sh basic release incremental generic
	fi
fi

if [ "$1" == "--build" ] || [ "$1" == "-b" ]
then
	./build_template.sh basic release incremental generic
	shift
fi

ARCHIVE="2100.9999_template_android_4.0.3_basic.tar.bz"

cd template || exit

tar cvjf ${ARCHIVE} .

ls -l ${ARCHIVE}

if [ "$1" == "--upload" ] || [ "$1" == "-u" ]
then
	echo "Uploading ..."
	aws s3 cp "$ARCHIVE" s3://ansca-templates/2100.9999/
else
	echo "Upload with: aws s3 cp template/$ARCHIVE s3://ansca-templates/2100.9999/"
fi

if [ -d $AS2BACKUP ]
then
	mv $AS2BACKUP $ASSETS2 
fi
