//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Simulator.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SIMULATOR_MENU              128
#define IDR_ACTIVEWND                   129
#define IDR_HOME_MENU                   129
#define IDS_BUILDWEBUPSELL              129
#define IDS_INVALID_WEB_APP_VERSION_NUMBER 130
#define IDS_INVALID_LINUX_APP_VERSION_NUMBER 131
#define IDS_INVALID_NXS_APP_VERSION_NUMBER 132
#define IDD_BUILD_DROID                 311
#define IDD_LOGIN                       313
#define IDD_LICENSE                     314
#define IDD_PROGRESSMSG                 315
#define IDD_PASSWORD                    316
#define IDD_MESSAGE                     317
#define IDI_ANIMATION                   329
#define IDI_BUTTONS                     330
#define IDI_GPS                         331
#define IDI_MOVIECLIP                   332
#define IDI_POLYLINES                   333
#define IDD_PREFERENCES                 334
#define IDI_BRIDGE                      335
#define IDI_CHAINS                      336
#define IDI_EGGBREAKER                  337
#define IDI_JUNGLESCENE                 338
#define IDI_ICON5                       339
#define IDI_SIMPLEPOOL                  340
#define IDD_DEVPASSWORD                 341
#define IDD_BUILD_PROGRESS              346
#define IDD_NEW_PROJECT                 349
#define IDD_SELECT_SAMPLE_PROJECT       350
#define IDI_FACEBOOK                    351
#define IDI_OPEN_FEINT                  352
#define IDI_MULTITOUCH                  353
#define IDI_ALERT                       354
#define IDI_CAMERA                      355
#define IDI_TEXT_INPUT                  356
#define IDI_FISHIES                     357
#define IDI_COMPASS                     358
#define IDI_AUDIO                       359
#define IDI_FRUIT                       360
#define IDI_MULTIPUCK                   361
#define IDI_CRATE                       362
#define IDI_BALLOON                     363
#define IDI_PLATFORM                    364
#define IDI_CAN                         365
#define IDI_INTERNET                    366
#define IDI_SPOTLIGHT                   367
#define IDI_GLOBE                       368
#define IDI_ACTIVITY_INDICATOR          369
#define IDI_MICROPHONE                  370
#define IDD_BUILD_LINUX                 371
#define IDI_INNERACTIVE                 372
#define IDI_TWITTER                     373
#define IDI_MAIL                        374
#define IDD_RELAUNCH_PREF               375
#define IDD_BUILD_WEB                   376
#define IDD_CUSTOM_DEVICE               377
#define IDD_BUILD_WIN32_APP             378
#define IDD_HTML_MESSAGE                379
#define IDD_BUILD_NXS              382
#define IDS_OPENFORBUILD_s              500
#define IDS_OPENMAINLUA                 501
#define IDS_ONLYMAINLUA                 502
#define IDS_EXPIRE                      503
#define IDS_HARDWARE_SUSPEND            504
#define IDS_RESUME                      505
#define IDS_HARDWARE_RESUME             506
#define IDS_VALID_PACKAGE               507
#define IDS_INVALID_KEYSTORE_s          508
#define IDS_CHOOSEFOLLOWING             509
#define IDS_LOGINSUCCESSFUL             510
#define IDS_LOGINFAILED                 511
#define IDS_LOGINBLACKLISTED            512
#define IDS_LOGINUNVERIFIED             513
#define IDS_TRIALEXPIRED                514
#define IDS_BASICEXPIRED                515
#define IDS_QUOTALIMIT                  516
#define IDS_PLATFORMMISMATCH            517
#define IDS_APIKEYINVALID               518
#define IDS_TOKENEXPIRED                519
#define IDS_PWDNOTSAVED                 520
#define IDS_AGREEMENTCHANGED            521
#define IDS_LOGINERROR                  522
#define IDS_DEAUTHORIZED                523
#define IDS_DEAUTHERROR                 524
#define IDS_DEAUTH_CONFIRM              525
#define IDS_BUILD_SUCCEEDED             526
#define IDS_BUILD_NOT_AUTH              527
#define IDS_LOGIN_INVALID               528
#define IDS_BUILD_FAILED                529
#define IDS_CONSOLE_FAILED              530
#define IDS_CONSOLE_FREE                531
#define IDS_DIR_s_NOTFOUND_INSTALL      532
#define IDS_FILE_s_NOTFOUND_INSTALL     533
#define IDS_INVALID_ALIAS               534
#define IDS_QUIT                        535
#define IDS_CONTINUE                    536
#define IDS_PURCHASE                    537
#define IDS_OK                          538
#define IDS_RENEW                       539
#define IDS_DOWNLOAD                    540
#define IDS_CANCEL                      541
#define IDS_REMOVE_s_APPDIR             542
#define IDS_STORED_PASSWORD_INVALID     543
#define IDS_DONE                        544
#define IDS_VIEW_EXPLORER               545
#define IDS_JDKNOTFOUND                 546
#define IDS_INSTALLNOW                  547
#define IDS_COULDNOTLOAD_s_ERR_d        548
#define IDS_FUNCTION_s_IN_s             549
#define IDS_APPCORRUPTED                550
#define IDS_CLICKBUYNOW                 551
#define IDS_BUYNOW                      552
#define IDS_VERIFY_PURCHASE             553
#define IDS_SUBSCRIPTION_EXPIRED        554
#define IDS_NEEDTORENEW                 555
#define IDS_ALREADYRENEWED              556
#define IDS_TRIAL_EXPIRED               557
#define IDS_OPEN_NOTE                   558
#define IDS_BUILD_NOTE                  559
#define IDS_STARTED_NOTE                560
#define IDS_PROGRAMMING_NOTE            561
#define IDS_CORONAGETRIAL               562
#define IDS_UPGRADE                     563
#define IDS_ALREADYUPGRADED             564
#define IDS_SUBSCRIBERGETRIAL           565
#define IDS_SUBSCRIBERGERENEW           566
#define IDS_CONTINUETRIAL               567
#define IDS_CORONATRIAL                 568
#define IDS_TRIALTHANKS_d               569
#define IDS_TRIALFUN_d                  570
#define IDS_BRIDGE_NOTE                 571
#define IDS_CHAINS_NOTE                 572
#define IDS_EGGBREAKER_NOTE             573
#define IDS_JUNGLESCENE_NOTE            574
#define IDS_SIMPLEPOOL_NOTE             575
#define IDS_ANIMATION_NOTE              576
#define IDS_BUTTONS_NOTE                577
#define IDS_MOVIECLIP_NOTE              578
#define IDS_GPS_NOTE                    579
#define IDS_POLYLINES_NOTE              580
#define IDS_CONNECTINGTOSERVER          582
#define IDS_CONSOLE_CREATE              583
#define IDS_NO_INTERNET                 584
#define IDS_UNKNOWNERROR                585
#define IDS_STILLTRIAL                  586
#define IDS_THANKSPURCHASE              587
#define IDS_SET_JAVAHOME_s              588
#define IDS_ASSOCLUA                    589
#define IDS_OPENPROJECTINEDITOR         590
#define IDS_TRIALBUILDSONLY             591
#define IDS_BUILDUPSELL                 592
#define IDS_TRIALBUILD                  593
#define IDS_KEYSTORENOTFOUND_s          602
#define IDS_ANDROIDBUILD                603
#define IDS_KEYSTORE_ATLEASTONE         604
#define IDS_OPENGL_VERSION_WARNING      605
#define IDS_WARNING                     606
#define IDS_UNKNOWN                     607
#define IDS_APP_NEEDS_REAUTHORIZATION   608
#define IDS_SUBSCRIPTION_EXPIRED_FOR_BUILD 609
#define IDS_BUILD_VERSION_MISMATCH_ERROR 610
#define IDS_BUILD_ERROR_FORMAT_MESSAGE  611
#define IDS_BUILD_APP_NAME_NOT_PROVIDED 612
#define IDS_BUILD_VERSION_NUMBER_NOT_PROVIDED 613
#define IDS_BUILD_PACKAGE_NAME_NOT_PROVIDED 614
#define IDS_INVALID_ANDROID_APP_VERSION_NUMBER 615
#define IDS_ANDROID_KEYSTORE_FILE_NOT_PROVIDED 616
#define IDS_BUILD_TARGET_OS_NOT_SELECTED 617
#define IDS_ANDROID_KEYALIAS_NOT_SELECTED 618
#define IDS_BUILD_PATH_NOT_PROVIDED     619
#define IDS_ANDROID_KEYSTORE_FILE_NOT_FOUND 620
#define IDS_BUILD_PATH_CREATION_FAILED  621
#define IDS_INVALID_ANDROID_PROJECT_FILES 622
#define IDS_IGNORE                      623
#define IDS_DAILY_BUILD_AVAILABLE_TO_SUBSCRIBERS_ONLY 624
#define IDS_TITLE_UPGRADE_CORONA        625
#define IDS_DEVICE_NOT_AVAILABLE_TO_TRIAL_USERS 626
#define IDS_DEVICE_NOT_AVAILABLE_TO_X_SUBSCRIBERS 627
#define IDS_TITLE_BUY_CORONA            628
#define IDS_TRIAL_BUILD_COUNTDOWN       629
#define IDS_TITLE_SIMULATOR_OUTPUT      630
#define IDS_ANDROID                     631
#define IDS_AMAZON_SLASH_KINDLE         632
#define IDS_SCREEN_SIZE_PHONE           633
#define IDS_SCREEN_SIZE_TABLET          634
#define IDS_SCREEN_SIZE_CUSTOM          635
#define IDS_PROJECT_PATH_NOT_PROVIDED   636
#define IDS_PROJECT_PATH_CREATION_FAILED 637
#define IDS_PROJECT_SCREEN_WIDTH_IS_INVALID 638
#define IDS_PROJECT_SCREEN_HEIGHT_IS_INVALID 639
#define IDS_PROJECT_PATH_ALREADY_TAKEN  640
#define IDS_PROJECT_FILES_CREATION_FAILED 641
#define IDS_PROJECT_APPLICATION_NAME_INVALID 642
#define IDS_SELECT_ROOT_PROJECT_FOLDER_DESCRIPTION 643
#define IDS_SELECT_BUILD_OUTPUT_FOLDER_DESCRIPTION 644
#define IDS_BUILD_VERSION_NAME_NOT_PROVIDED 645
#define IDS_FILTER_ALL_PROJECTS         646
#define IDS_MUST_SELECT_SAMPLE_PROJECT  647
#define IDS_UNABLE_TO_FIND_SAMPLE_PROJECTS_DIRECTORY 648
#define IDS_NOOK                        649
#define IDS_SIMULATOR_FILES             650
#define IDS_BUILD_SETTINGS_FILE_ERROR   651
#define IDS_BUILD_TARGET_APP_STORE_NOT_SELECTED 652
#define IDS_SUBSCRIPTION_EXPIRING       653
#define IDS_RENEW_NOW                   654
#define IDS_REMIND_ME_LATER             655
#define IDS_SUBSCRIPTION_EXPIRING_SOON  656
#define IDS_SUBSCRIPTION_EXPIRING_DAYS  657
#define IDS_SUBSCRIPTION_EXPIRED_MODE   658
#define IDS_BUILD_PATH_INVALID          659
#define IDS_LOGIN                       660
#define IDS_NOT_LOGGED_IN               661
#define IDS_LOGGED_IN_AS                662
#define IDS_SUSPENDED                   663
#define IDS_OPENGL21_VERSION_WARNING    664
#define IDS_MONETIZATION_WARNING        665
#define IDS_ENABLE_MONETIZATION         666
#define IDS_BUILD_EXE_FILE_NAME_NOT_PROVIDED 667
#define IDS_BUILD_EXE_FILE_NAME_CHARS_INVALID 668
#define IDS_BUILD_WIN32_VERSION_STRING_INVALID 669
#define IDS_BUILD_VERSION_STRING_NOT_PROVIDED 670
#define IDS_CANNOT_BUILD_WITHOUT_PLUGINS 671
#define IDS_CREATE_LIVE_BUILD           672
#define IDS_CREATE_LIVE_BUILD_WARNING   673
#define IDS_OPEN_URL_HTML               674
#define IDS_ANDROID_BUILD               675
#define IDS_ANDROID_SDK_LICENSE         676
#define IDS_BUILD_NMETA_NAME_NOT_PROVIDED 677
#define IDS_APK_NOT_FOUND               678
#define IDC_LINK_ANSCAMOBILE            1000
#define IDC_BUILD_APPNAME               1001
#define IDC_BUILD_VERSION_CODE          1002
#define IDC_BUILD_PACKAGE               1003
#define IDC_BUILD_KEYSTORE              1004
#define IDC_BUILD_SAVETO                1005
#define IDC_BUILD_KEYALIAS              1007
#define IDC_BUILD_BROWSE_KEYSTORE       1009
#define IDC_BUILD_BROWSE_SAVETO         1010
#define IDC_BUILD_PROJECTPATH           1012
#define IDC_KEY                         1015
#define IDC_PASSWORD                    1016
#define IDC_SAVEPASSWORD                1017
#define IDC_LOGIN_EMAIL                 1019
#define IDC_LOGIN_PASSWORD              1020
#define IDC_LICENSE                     1022
#define IDC_PROGRESS                    1023
#define IDC_LOGIN_REGISTER              1024
#define IDC_MSG_ICON                    1025
#define IDC_MSG_TEXT                    1026
#define IDC_ABOUT_VERSION               1027
#define IDC_WELCOME_BUILD               1038
#define IDC_WELCOME_OPEN4               1039
#define IDC_ANSCALOGO                   1041
#define IDC_COMMAND1                    1042
#define IDC_DEAUTHORIZE                 1043
#define IDC_ANALYTICS                   1044
#define IDC_NOWELCOME                   1045
#define IDC_PROGRESSWND_TEXT            1045
#define IDC_SHOW_RUNTIME_ERRORS         1046
#define IDC_AUTO_OPEN_LAST_PROJECT      1047
#define ID_MSG_BUTTON2                  1049
#define ID_MSG_BUTTON3                  1050
#define IDC_COPYRIGHT                   1052
#define IDC_PICTURE_BOX                 1054
#define IDC_PICTURE_FRAME               1054
#define IDC_STATUS_MESSAGE              1055
#define IDC_APP_NAME_LABEL              1056
#define IDC_APP_NAME_EDIT_BOX           1057
#define IDC_TEMPLATE_GROUP_BOX          1058
#define IDC_TEMPLATE_BLANK              1059
#define IDC_TEMPLATE_TAB_BAR            1060
#define IDC_TEMPLATE_GAME               1061
#define IDC_TEMPLATE_EBOOK              1062
#define IDC_SCREEN_SIZE_GROUP_BOX       1064
#define IDC_SCREEN_SIZE_COMBO_BOX       1065
#define IDC_SCREEN_WIDTH_LABEL          1066
#define IDC_SCREEN_WIDTH_EDIT_BOX       1067
#define IDC_SCREEN_HEIGHT_LABEL         1068
#define IDC_SCREEN_HEIGHT_EDIT_BOX      1069
#define IDC_ORIENTATION_GROUP_BOX       1070
#define IDC_APP_LOCATION_LABEL          1071
#define IDC_APP_LOCATION_EDIT_BOX       1072
#define IDC_BROWSE_BUTTON               1073
#define IDC_ORIENTATION_UPRIGHT         1074
#define IDC_ORIENTATION_SIDEWAYS        1075
#define IDC_TEMPLATE_BLANK_LABEL        1076
#define IDC_DIVIDING_LINE               1077
#define IDC_TEMPLATE_TAB_BAR_LABEL      1078
#define IDC_TEMPLATE_GAME_LABEL         1079
#define IDC_TEMPLATE_EBOOK_LABEL        1080
#define IDC_BUILD_VERSION_NAME          1082
#define IDC_SAMPLE_LIST                 1083
#define IDC_FILTER_COMBO_BOX            1084
#define IDC_BUILD_TARGET_APP_STORE      1085
#define IDC_USER_ACCOUNT                1086
#define IDC_SUBSCRIPTION                1087
#define IDC_SIM_RELAUNCH_ALWAYS         1088
#define IDC_SIM_RELAUNCH_NEVER          1089
#define IDC_SIM_RELAUNCH_ASK            1090
#define IDC_CHECK1                      1091
#define IDC_ENABLE_MONETIZATION         1091
#define IDC_REMEMBER_PREF               1092
#define IDC_CD_DEVICE_NAME              1093
#define IDC_CD_SCREEN_WIDTH             1094
#define IDC_CD_SCREEN_HEIGHT            1095
#define IDC_BUILD_EXE_FILE_NAME         1096
#define IDC_BUILD_COMPANY_NAME          1097
#define IDC_BUILD_COPYRIGHT             1098
#define IDC_EDIT4                       1099
#define IDC_BUILD_APP_DESCRIPTION       1099
#define IDC_WEB_BROWSER                 1100
#define IDC_CREATE_LIVE_BUILD           1101
#define IDC_CD_PLATFORM                 1102
#define IDC_STOP_BUILD                  1103
#define IDC_INCLUDE_STANDART_RESOURCES  1104
#define IDC_CREATE_FB_INSTANT_ARCHIVE   1105
#define IDC_BUILD_NMETA_PATH            1106
#define IDC_ON_COMPLETE_OPTIONS         1107
#define IDC_COPY_TO_DEVICE              1108
#define IDC_SHOW_IN_FILES               1109
#define IDC_DO_NOTHING                  1110
#define ID_Menu                         32771
#define ID_FILE_OPENFORBUILD            32772
#define ID_FILE_RELAUNCH                32774
#define ID_VIEW_ROTATELEFT              32775
#define ID_VIEW_ROTATERIGHT             32776
#define ID_VIEW_SHAKE                   32777
#define ID_VIEW_SUSPEND                 32778
#define ID_HELP_HELP                    32779
#define ID_WINDOW_ZOOMIN                32780
#define ID_WINDOW_ZOOMOUT               32781
#define ID_WINDOW_VIEWAS                32782
#define ID_WINDOW_VIEWING               32783
#define ID_HELP_DEAUTHORIZE             32784
#define ID_FILE_SHOWPROJECTSANDBOX      32796
#define ID_FILE_PREFERENCES             32797
#define ID_FILE_OPENINEDITOR            32799
#define ID_VIEW_WELCOMESCREEN           32800
#define ID_VIEW_DEMO                    32801
#define ID_FILE_NEWPROJECT              32802
#define ID_VIEW_HOME_SCREEN             32803
#define ID_VIEW_SAMPLEPROJECTS          32804
#define ID_VIEW_SAMPLE_PROJECTS         32805
#define ID_HELP_SAMPLEPROJECTS          32806
#define ID_FILE_OPEN_SAMPLE             32807
#define ID_FILE_OPEN_SAMPLE_PROJECT     32808
#define ID_FILE_OPENINWINDOWSEXPLORER   32809
#define ID_FILE_SHOW_PROJECT_FILES      32810
#define ID_BUILD_FOR_ANDROID            32811
#define ID_BUILD_FOR_WEB                32812
#define ID_BUILD_FOR_WIN32              32813
#define ID_VIEW_VIEWAS                  32814
#define ID_VIEWAS_                      32815
#define ID_VIEWAS_PLACEHOLDER           32816
#define ID_VIEW_NAVIGATE_BACK           32817
#define ID_FILE_CLEARPROJECTSANDBOX     32818
#define ID_VIEW_CONSOLE                 32819
#define ID_BUILD_FOR_LINUX              32820
#define ID_BUILD_FOR_NXS           32821
#define ID_VIEWAS_BEGIN                 32900
#define ID_VIEWAS_CUSTOMDEVICE          32998
#define ID_VIEWAS_END                   32999



// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        383
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           382
#endif
#endif
