# GNU Make project makefile autogenerated by Premake
ifndef config
  config=Debug
endif

ifndef verbose
  SILENT = @
endif

CC = gcc
CXX = g++
AR = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),Debug)
  OBJDIR     = obj/Debug/Box2D
  # TARGETDIR  = ../../../Build/gmake/bin/Debug
  TARGETDIR  = obj/Debug
  TARGET     = $(TARGETDIR)/libBox2D.a
  DEFINES   += -DRtt_DEBUG -DLUA_USE_APICHECK
  INCLUDES  += -I../../../external/Box2D
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-exceptions -fno-rtti
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS)
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  #LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),Release)
  OBJDIR     = obj/Release/Box2D
  # TARGETDIR  = ../../../Build/gmake/bin/Release
  TARGETDIR  = obj/Release
  TARGET     = $(TARGETDIR)/libBox2D.a
  DEFINES   += -DNDEBUG
  INCLUDES  += -I../../../external/Box2D
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-exceptions -fno-rtti
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -Wl,-x
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  #LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/b2BroadPhase.o \
	$(OBJDIR)/b2CollideCircle.o \
	$(OBJDIR)/b2CollideEdge.o \
	$(OBJDIR)/b2CollidePolygon.o \
	$(OBJDIR)/b2Collision.o \
	$(OBJDIR)/b2Distance.o \
	$(OBJDIR)/b2DynamicTree.o \
	$(OBJDIR)/b2TimeOfImpact.o \
	$(OBJDIR)/b2ChainShape.o \
	$(OBJDIR)/b2CircleShape.o \
	$(OBJDIR)/b2EdgeShape.o \
	$(OBJDIR)/b2PolygonShape.o \
	$(OBJDIR)/b2BlockAllocator.o \
	$(OBJDIR)/b2Draw.o \
	$(OBJDIR)/b2FreeList.o \
	$(OBJDIR)/b2Math.o \
	$(OBJDIR)/b2Settings.o \
	$(OBJDIR)/b2StackAllocator.o \
	$(OBJDIR)/b2Timer.o \
	$(OBJDIR)/b2TrackedBlock.o \
	$(OBJDIR)/b2Body.o \
	$(OBJDIR)/b2ContactManager.o \
	$(OBJDIR)/b2Fixture.o \
	$(OBJDIR)/b2Island.o \
	$(OBJDIR)/b2World.o \
	$(OBJDIR)/b2WorldCallbacks.o \
	$(OBJDIR)/b2ChainAndCircleContact.o \
	$(OBJDIR)/b2ChainAndPolygonContact.o \
	$(OBJDIR)/b2CircleContact.o \
	$(OBJDIR)/b2Contact.o \
	$(OBJDIR)/b2ContactSolver.o \
	$(OBJDIR)/b2EdgeAndCircleContact.o \
	$(OBJDIR)/b2EdgeAndPolygonContact.o \
	$(OBJDIR)/b2PolygonAndCircleContact.o \
	$(OBJDIR)/b2PolygonContact.o \
	$(OBJDIR)/b2DistanceJoint.o \
	$(OBJDIR)/b2FrictionJoint.o \
	$(OBJDIR)/b2GearJoint.o \
	$(OBJDIR)/b2Joint.o \
	$(OBJDIR)/b2MotorJoint.o \
	$(OBJDIR)/b2MouseJoint.o \
	$(OBJDIR)/b2PrismaticJoint.o \
	$(OBJDIR)/b2PulleyJoint.o \
	$(OBJDIR)/b2RevoluteJoint.o \
	$(OBJDIR)/b2RopeJoint.o \
	$(OBJDIR)/b2WeldJoint.o \
	$(OBJDIR)/b2FakeJoint.o \
	$(OBJDIR)/b2WheelJoint.o \
	$(OBJDIR)/b2Particle.o \
	$(OBJDIR)/b2ParticleAssembly.o \
	$(OBJDIR)/b2ParticleGroup.o \
	$(OBJDIR)/b2ParticleSystem.o \
	$(OBJDIR)/b2VoronoiDiagram.o \
	$(OBJDIR)/b2Rope.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking Box2D
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Box2D
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -MMD -MP $(DEFINES) $(INCLUDES) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/b2BroadPhase.o: ../../../external/Box2D/Box2D/Collision/b2BroadPhase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2CollideCircle.o: ../../../external/Box2D/Box2D/Collision/b2CollideCircle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2CollideEdge.o: ../../../external/Box2D/Box2D/Collision/b2CollideEdge.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2CollidePolygon.o: ../../../external/Box2D/Box2D/Collision/b2CollidePolygon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Collision.o: ../../../external/Box2D/Box2D/Collision/b2Collision.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Distance.o: ../../../external/Box2D/Box2D/Collision/b2Distance.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2DynamicTree.o: ../../../external/Box2D/Box2D/Collision/b2DynamicTree.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2TimeOfImpact.o: ../../../external/Box2D/Box2D/Collision/b2TimeOfImpact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ChainShape.o: ../../../external/Box2D/Box2D/Collision/Shapes/b2ChainShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2CircleShape.o: ../../../external/Box2D/Box2D/Collision/Shapes/b2CircleShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2EdgeShape.o: ../../../external/Box2D/Box2D/Collision/Shapes/b2EdgeShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2PolygonShape.o: ../../../external/Box2D/Box2D/Collision/Shapes/b2PolygonShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2BlockAllocator.o: ../../../external/Box2D/Box2D/Common/b2BlockAllocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Draw.o: ../../../external/Box2D/Box2D/Common/b2Draw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2FreeList.o: ../../../external/Box2D/Box2D/Common/b2FreeList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Math.o: ../../../external/Box2D/Box2D/Common/b2Math.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Settings.o: ../../../external/Box2D/Box2D/Common/b2Settings.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2StackAllocator.o: ../../../external/Box2D/Box2D/Common/b2StackAllocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2TrackedBlock.o: ../../../external/Box2D/Box2D/Common/b2TrackedBlock.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Timer.o: ../../../external/Box2D/Box2D/Common/b2Timer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Body.o: ../../../external/Box2D/Box2D/Dynamics/b2Body.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ContactManager.o: ../../../external/Box2D/Box2D/Dynamics/b2ContactManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Fixture.o: ../../../external/Box2D/Box2D/Dynamics/b2Fixture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Island.o: ../../../external/Box2D/Box2D/Dynamics/b2Island.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2World.o: ../../../external/Box2D/Box2D/Dynamics/b2World.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2WorldCallbacks.o: ../../../external/Box2D/Box2D/Dynamics/b2WorldCallbacks.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ChainAndCircleContact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ChainAndPolygonContact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2CircleContact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2CircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Contact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2Contact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ContactSolver.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2ContactSolver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2EdgeAndCircleContact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2EdgeAndPolygonContact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2PolygonAndCircleContact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2PolygonContact.o: ../../../external/Box2D/Box2D/Dynamics/Contacts/b2PolygonContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2DistanceJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2DistanceJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2FrictionJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2FrictionJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2GearJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2GearJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Joint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2Joint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2MotorJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2MotorJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2MouseJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2MouseJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2PrismaticJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2PulleyJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2PulleyJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2RevoluteJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2RopeJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2RopeJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2WeldJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2WeldJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2FakeJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2FakeJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2WheelJoint.o: ../../../external/Box2D/Box2D/Dynamics/Joints/b2WheelJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Particle.o: ../../../external/Box2D/Box2D/Particle/b2Particle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ParticleAssembly.o: ../../../external/Box2D/Box2D/Particle/b2ParticleAssembly.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ParticleGroup.o: ../../../external/Box2D/Box2D/Particle/b2ParticleGroup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2ParticleSystem.o: ../../../external/Box2D/Box2D/Particle/b2ParticleSystem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2VoronoiDiagram.o: ../../../external/Box2D/Box2D/Particle/b2VoronoiDiagram.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Rope.o: ../../../external/Box2D/Box2D/Rope/b2Rope.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif
