# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

CC = gcc
CXX = g++
AR = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),Debug)
  OBJDIR     = obj/Debug/ratatouille
  # TARGETDIR  = ../../../Build/gmake/bin/Debug
  TARGETDIR  = obj/Debug
  TARGET     = $(TARGETDIR)/libratatouille.a
  DEFINES   += -DRtt_DEBUG -DLUA_USE_APICHECK -DRtt_EMSCRIPTEN_ENV
  INCLUDES  += -I../../../librtt -I../../../librtt/Core -I../../../external/lua-5.1.3/src -I.. -I../../../external/libpng1243b01 -I../../../external/zlib123 -I../../../external/libjpeg -I../../shared
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-exceptions -fno-rtti
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS)
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  #LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),Release)
  OBJDIR     = obj/Release/ratatouille
  # TARGETDIR  = ../../../Build/gmake/bin/Release
  TARGETDIR  = obj/Release
  TARGET     = $(TARGETDIR)/libratatouille.a
  DEFINES   += -DNDEBUG -DRtt_EMSCRIPTEN_ENV
  INCLUDES  += -I../../../librtt -I../../../librtt/Core -I../../../external/lua-5.1.3/src -I.. -I../../../external/libpng1243b01 -I../../../external/zlib123 -I../../../external/libjpeg -I../../shared
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-exceptions -fno-rtti
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -Wl,-x
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  #LINKCMD    = $(CC) -o $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/main.o \
	$(OBJDIR)/Rtt_EmscriptenAudioPlayer.o \
	$(OBJDIR)/Rtt_EmscriptenAudioRecorder.o \
	$(OBJDIR)/Rtt_EmscriptenBitmap.o \
	$(OBJDIR)/Rtt_EmscriptenCrypto.o \
	$(OBJDIR)/Rtt_EmscriptenData.o \
	$(OBJDIR)/Rtt_EmscriptenDevice.o \
	$(OBJDIR)/Rtt_EmscriptenDisplayObject.o \
	$(OBJDIR)/Rtt_EmscriptenEventSound.o \
	$(OBJDIR)/Rtt_EmscriptenFBConnect.o \
	$(OBJDIR)/Rtt_EmscriptenFont.o \
	$(OBJDIR)/Rtt_EmscriptenImageProvider.o \
	$(OBJDIR)/Rtt_EmscriptenMapViewObject.o \
	$(OBJDIR)/Rtt_EmscriptenPlatform.o \
	$(OBJDIR)/Rtt_EmscriptenRuntimeDelegate.o \
	$(OBJDIR)/Rtt_EmscriptenScreenSurface.o \
	$(OBJDIR)/Rtt_EmscriptenStore.o \
	$(OBJDIR)/Rtt_EmscriptenStoreProvider.o \
	$(OBJDIR)/Rtt_EmscriptenStoreTransaction.o \
	$(OBJDIR)/Rtt_EmscriptenTextBoxObject.o \
	$(OBJDIR)/Rtt_EmscriptenVideoObject.o \
	$(OBJDIR)/Rtt_EmscriptenVideoPlayer.o \
	$(OBJDIR)/Rtt_EmscriptenVideoProvider.o \
	$(OBJDIR)/Rtt_EmscriptenWebPopup.o \
	$(OBJDIR)/Rtt_EmscriptenWebViewObject.o \
	$(OBJDIR)/Rtt_EmscriptenContainer.o \
	$(OBJDIR)/Rtt_EmscriptenCPluginLoader.o \
	$(OBJDIR)/Rtt_EmscriptenJSPluginLoader.o \
	$(OBJDIR)/Rtt_EmscriptenContainer.o \
	$(OBJDIR)/Rtt_LuaLibWebAudio.o \
	$(OBJDIR)/Rtt_PlatformWebAudioPlayer.o \
	$(OBJDIR)/Rtt_EmscriptenContext.o \
	$(OBJDIR)/NetworkLibrary.o \
	$(OBJDIR)/EmscriptenNetworkSupport.o \
	$(OBJDIR)/network_luaload.o \
	$(OBJDIR)/Rtt_BitmapUtils.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking ratatouille
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning ratatouille
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -MMD -MP $(DEFINES) $(INCLUDES) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/main.o: ../main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenAudioPlayer.o: ../Rtt_EmscriptenAudioPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenAudioRecorder.o: ../Rtt_EmscriptenAudioRecorder.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenBitmap.o: ../Rtt_EmscriptenBitmap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenCrypto.o: ../Rtt_EmscriptenCrypto.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenData.o: ../Rtt_EmscriptenData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenDevice.o: ../Rtt_EmscriptenDevice.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenDisplayObject.o: ../Rtt_EmscriptenDisplayObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenEventSound.o: ../Rtt_EmscriptenEventSound.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenFBConnect.o: ../Rtt_EmscriptenFBConnect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenFont.o: ../Rtt_EmscriptenFont.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenImageProvider.o: ../Rtt_EmscriptenImageProvider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenMapViewObject.o: ../Rtt_EmscriptenMapViewObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenPlatform.o: ../Rtt_EmscriptenPlatform.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenRuntimeDelegate.o: ../Rtt_EmscriptenRuntimeDelegate.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenCPluginLoader.o: ../Rtt_EmscriptenCPluginLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenJSPluginLoader.o: ../Rtt_EmscriptenJSPluginLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenScreenSurface.o: ../Rtt_EmscriptenScreenSurface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenStore.o: ../Rtt_EmscriptenStore.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenStoreProvider.o: ../Rtt_EmscriptenStoreProvider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenStoreTransaction.o: ../Rtt_EmscriptenStoreTransaction.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenTextBoxObject.o: ../Rtt_EmscriptenTextBoxObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenVideoObject.o: ../Rtt_EmscriptenVideoObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenContext.o: ../Rtt_EmscriptenContext.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenVideoPlayer.o: ../Rtt_EmscriptenVideoPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenVideoProvider.o: ../Rtt_EmscriptenVideoProvider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenWebPopup.o: ../Rtt_EmscriptenWebPopup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmscriptenWebViewObject.o: ../Rtt_EmscriptenWebViewObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"
	
$(OBJDIR)/Rtt_EmscriptenContainer.o: ../Rtt_EmscriptenContainer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"
	
$(OBJDIR)/Rtt_LuaLibWebAudio.o: ../Rtt_LuaLibWebAudio.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"
	
$(OBJDIR)/Rtt_PlatformWebAudioPlayer.o: ../Rtt_PlatformWebAudioPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/NetworkLibrary.o: ../../../plugins/network/emscripten/NetworkLibrary.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/EmscriptenNetworkSupport.o: ../../../plugins/network/emscripten/EmscriptenNetworkSupport.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/network_luaload.o: ../network_luaload.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_BitmapUtils.o: ../../shared/Rtt_BitmapUtils.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif
