# GNU Make project makefile autogenerated by Premake
ifndef config
  config=Debug
endif

ifndef verbose
  SILENT = @
endif

CC = gcc
CXX = g++
AR = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),Debug)
  OBJDIR     = obj/Debug/rtt
  # TARGETDIR  = ../../../Build/gmake/bin/Debug
  TARGETDIR  = obj/Debug
  TARGET     = $(TARGETDIR)/librtt.a
  DEFINES   += -DRtt_DEBUG -DLUA_USE_APICHECK -DRtt_EMSCRIPTEN_ENV
  INCLUDES  += -I../ -I../../../librtt -I../../../librtt/Corona -I../../../external/b2Separator-cpp -I../../../external/Box2D -I../../../external/fft -I../../../external/lua-5.1.3/src -I../../../external/luasocket/src -I../../../external/smoothpolygon -I../system/include
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -g
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-exceptions -fno-rtti
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS)
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  #LINKCMD    = $(CC) $(OBJECTS) -o $(TARGET)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),Release)
  OBJDIR     = obj/Release/rtt
  # TARGETDIR  = ../../../Build/gmake/bin/Release
  TARGETDIR  = obj/Release
  TARGET     = $(TARGETDIR)/librtt.a
  DEFINES   += -DNDEBUG -DRtt_EMSCRIPTEN_ENV
  INCLUDES  += -I../ -I../../../librtt -I../../../librtt/Corona -I../../../external/b2Separator-cpp -I../../../external/Box2D -I../../../external/fft -I../../../external/lua-5.1.3/src -I../../../external/luasocket/src -I../../../external/smoothpolygon -I../system/include
  ALL_CPPFLAGS  += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS    += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O2
  ALL_CXXFLAGS  += $(CXXFLAGS) $(ALL_CFLAGS) -fno-exceptions -fno-rtti
  ALL_RESFLAGS  += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS   += $(LDFLAGS) -Wl,-x
  LDDEPS    +=
  LIBS      += $(LDDEPS)
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  #LINKCMD    = $(CC) $(OBJECTS) -o $(TARGET)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/Rtt_Preference.o \
	$(OBJDIR)/Rtt_PreferenceCollection.o \
	$(OBJDIR)/Rtt_PreferenceValue.o \
	$(OBJDIR)/Rtt_TesselatorMesh.o \
	$(OBJDIR)/Rtt_OperationResult.o \
	$(OBJDIR)/Rtt_ShapeAdapterMesh.o \
	$(OBJDIR)/Rtt_LuaCoronaBaseLib.o \
	$(OBJDIR)/Rtt_Assert.o \
	$(OBJDIR)/Rtt_Fixed.o \
	$(OBJDIR)/Rtt_FixedMath.o \
	$(OBJDIR)/Rtt_Math.o \
	$(OBJDIR)/Rtt_Time.o \
	$(OBJDIR)/Rtt_VersionTimestamp.o \
	$(OBJDIR)/CoronaAssert.o \
	$(OBJDIR)/CoronaLog.o \
	$(OBJDIR)/CoronaVersion.o \
	$(OBJDIR)/b2GLESDebugDraw.o \
	$(OBJDIR)/Rtt_Archive.o \
	$(OBJDIR)/Rtt_CachedPath.o \
	$(OBJDIR)/Rtt_DeviceOrientation.o \
	$(OBJDIR)/Rtt_DisplayObjectExtensions.o \
	$(OBJDIR)/Rtt_Event.o \
	$(OBJDIR)/Rtt_ExplicitTemplates.o \
	$(OBJDIR)/Rtt_FilePath.o \
	$(OBJDIR)/Rtt_FillTesselatorStream.o \
	$(OBJDIR)/Rtt_GPUStream.o \
	$(OBJDIR)/Rtt_HitTestObject.o \
	$(OBJDIR)/Rtt_KeyName.o \
	$(OBJDIR)/Rtt_Lua.o \
	$(OBJDIR)/Rtt_LuaAssert.o \
	$(OBJDIR)/Rtt_LuaAux.o \
	$(OBJDIR)/Rtt_LuaContainer.o \
	$(OBJDIR)/Rtt_LuaContext.o \
	$(OBJDIR)/Rtt_LuaData.o \
	$(OBJDIR)/Rtt_LuaLibCrypto.o \
	$(OBJDIR)/Rtt_LuaLibFacebook.o \
	$(OBJDIR)/Rtt_LuaLibFlurry.o \
	$(OBJDIR)/Rtt_LuaLibGameNetwork.o \
	$(OBJDIR)/Rtt_LuaLibInAppStore.o \
	$(OBJDIR)/Rtt_LuaLibMedia.o \
	$(OBJDIR)/Rtt_LuaLibNative.o \
	$(OBJDIR)/Rtt_LuaLibPhysics.o \
	$(OBJDIR)/Rtt_LuaLibSQLite.o \
	$(OBJDIR)/Rtt_LuaLibSystem.o \
	$(OBJDIR)/Rtt_LuaProxy.o \
	$(OBJDIR)/Rtt_LuaProxyVTable.o \
	$(OBJDIR)/Rtt_LuaResource.o \
	$(OBJDIR)/Rtt_LuaResourceOwner.o \
	$(OBJDIR)/Rtt_LuaTableIterator.o \
	$(OBJDIR)/Rtt_LuaUserdataProxy.o \
	$(OBJDIR)/Rtt_Matrix.o \
	$(OBJDIR)/Rtt_ParticleSystemObject.o \
	$(OBJDIR)/Rtt_PhysicsContact.o \
	$(OBJDIR)/Rtt_PhysicsContactListener.o \
	$(OBJDIR)/Rtt_PhysicsJoint.o \
	$(OBJDIR)/Rtt_PhysicsWorld.o \
	$(OBJDIR)/Rtt_PlatformAudioPlayer.o \
	$(OBJDIR)/Rtt_PlatformAudioRecorder.o \
	$(OBJDIR)/Rtt_PlatformAudioSessionManager.o \
	$(OBJDIR)/Rtt_PlatformData.o \
	$(OBJDIR)/Rtt_PlatformDisplayObject.o \
	$(OBJDIR)/Rtt_PlatformEventSound.o \
	$(OBJDIR)/Rtt_PlatformExitCallback.o \
	$(OBJDIR)/Rtt_PlatformFBConnect.o \
	$(OBJDIR)/Rtt_PlatformFont.o \
	$(OBJDIR)/Rtt_PlatformImageProvider.o \
	$(OBJDIR)/Rtt_PlatformInAppStore.o \
	$(OBJDIR)/Rtt_PlatformLocation.o \
	$(OBJDIR)/Rtt_PlatformModalInteraction.o \
	$(OBJDIR)/Rtt_PlatformNotifier.o \
	$(OBJDIR)/Rtt_PlatformReachability.o \
	$(OBJDIR)/Rtt_PlatformSurface.o \
	$(OBJDIR)/Rtt_PlatformTimer.o \
	$(OBJDIR)/Rtt_PlatformVideoPlayer.o \
	$(OBJDIR)/Rtt_PlatformVideoProvider.o \
	$(OBJDIR)/Rtt_PlatformWebPopup.o \
	$(OBJDIR)/Rtt_Profiling.o \
	$(OBJDIR)/Rtt_RenderingStream.o \
	$(OBJDIR)/Rtt_Resource.o \
	$(OBJDIR)/Rtt_Runtime.o \
	$(OBJDIR)/Rtt_RuntimeDelegate.o \
	$(OBJDIR)/Rtt_Scheduler.o \
	$(OBJDIR)/Rtt_SimpleCachedPath.o \
	$(OBJDIR)/Rtt_StrokeTesselatorStream.o \
	$(OBJDIR)/Rtt_TesselatorStream.o \
	$(OBJDIR)/Rtt_Transform.o \
	$(OBJDIR)/Rtt_Allocator.o \
	$(OBJDIR)/Rtt_Array.o \
	$(OBJDIR)/Rtt_ArrayTuple.o \
	$(OBJDIR)/Rtt_ArrayTupleStruct.o \
	$(OBJDIR)/Rtt_AutoResource.o \
	$(OBJDIR)/Rtt_FileSystem.o \
	$(OBJDIR)/Rtt_FixedBlockAllocator.o \
	$(OBJDIR)/Rtt_Geometry.o \
	$(OBJDIR)/Rtt_RefCount.o \
	$(OBJDIR)/Rtt_ResourceHandle.o \
	$(OBJDIR)/Rtt_SharedCount.o \
	$(OBJDIR)/Rtt_String.o \
	$(OBJDIR)/Rtt_StringHash.o \
	$(OBJDIR)/Rtt_UseCount.o \
	$(OBJDIR)/Rtt_WeakCount.o \
	$(OBJDIR)/CoronaEvent.o \
	$(OBJDIR)/CoronaLibrary.o \
	$(OBJDIR)/CoronaLua.o \
	$(OBJDIR)/CoronaMemory.o \
	$(OBJDIR)/Rtt_BitmapMask.o \
	$(OBJDIR)/Rtt_BitmapPaint.o \
	$(OBJDIR)/Rtt_BitmapPaintAdapter.o \
	$(OBJDIR)/Rtt_ImageSheetPaintAdapter.o \
	$(OBJDIR)/Rtt_BufferBitmap.o \
	$(OBJDIR)/Rtt_CameraPaint.o \
	$(OBJDIR)/Rtt_ClosedPath.o \
	$(OBJDIR)/Rtt_CompositeObject.o \
	$(OBJDIR)/Rtt_CompositePaint.o \
	$(OBJDIR)/Rtt_ContainerObject.o \
	$(OBJDIR)/Rtt_CPUResourcePool.o \
	$(OBJDIR)/Rtt_Display.o \
	$(OBJDIR)/Rtt_DisplayDefaults.o \
	$(OBJDIR)/Rtt_DisplayObject.o \
	$(OBJDIR)/Rtt_DisplayPath.o \
	$(OBJDIR)/Rtt_EmbossedTextObject.o \
	$(OBJDIR)/Rtt_EmitterObject.o \
	$(OBJDIR)/Rtt_GradientPaint.o \
	$(OBJDIR)/Rtt_GradientPaintAdapter.o \
	$(OBJDIR)/Rtt_GroupObject.o \
	$(OBJDIR)/Rtt_ImageFrame.o \
	$(OBJDIR)/Rtt_ImageSheet.o \
	$(OBJDIR)/Rtt_ImageSheetPaint.o \
	$(OBJDIR)/Rtt_ImageSheetUserdata.o \
	$(OBJDIR)/Rtt_LineObject.o \
	$(OBJDIR)/Rtt_LuaLibDisplay.o \
	$(OBJDIR)/Rtt_LuaLibGraphics.o \
	$(OBJDIR)/Rtt_OpenPath.o \
	$(OBJDIR)/Rtt_Paint.o \
	$(OBJDIR)/Rtt_PaintAdapter.o \
	$(OBJDIR)/Rtt_PlatformBitmap.o \
	$(OBJDIR)/Rtt_PlatformBitmapTexture.o \
	$(OBJDIR)/Rtt_RectObject.o \
	$(OBJDIR)/Rtt_RectPath.o \
	$(OBJDIR)/Rtt_Scene.o \
	$(OBJDIR)/Rtt_Shader.o \
	$(OBJDIR)/Rtt_ShaderBuiltin.o \
	$(OBJDIR)/Rtt_ShaderCache.o \
	$(OBJDIR)/Rtt_ShaderComposite.o \
	$(OBJDIR)/Rtt_ShaderCompositeAdapter.o \
	$(OBJDIR)/Rtt_ShaderData.o \
	$(OBJDIR)/Rtt_ShaderDataAdapter.o \
	$(OBJDIR)/Rtt_ShaderFactory.o \
	$(OBJDIR)/Rtt_ShaderInput.o \
	$(OBJDIR)/Rtt_ShaderName.o \
	$(OBJDIR)/Rtt_ShaderProxy.o \
	$(OBJDIR)/Rtt_ShaderResource.o \
	$(OBJDIR)/Rtt_ShaderTypes.o \
	$(OBJDIR)/Rtt_ShapeAdapter.o \
	$(OBJDIR)/Rtt_ShapeAdapterCircle.o \
	$(OBJDIR)/Rtt_ShapeAdapterPolygon.o \
	$(OBJDIR)/Rtt_ShapeAdapterRect.o \
	$(OBJDIR)/Rtt_ShapeAdapterRoundedRect.o \
	$(OBJDIR)/Rtt_ShapeObject.o \
	$(OBJDIR)/Rtt_ShapePath.o \
	$(OBJDIR)/Rtt_SnapshotObject.o \
	$(OBJDIR)/Rtt_SpriteObject.o \
	$(OBJDIR)/Rtt_SpritePlayer.o \
	$(OBJDIR)/Rtt_SpriteSourceFrame.o \
	$(OBJDIR)/Rtt_StageObject.o \
	$(OBJDIR)/Rtt_Tesselator.o \
	$(OBJDIR)/Rtt_TesselatorCircle.o \
	$(OBJDIR)/Rtt_TesselatorLine.o \
	$(OBJDIR)/Rtt_TesselatorPolygon.o \
	$(OBJDIR)/Rtt_TesselatorRect.o \
	$(OBJDIR)/Rtt_TesselatorRoundedRect.o \
	$(OBJDIR)/Rtt_TesselatorShape.o \
	$(OBJDIR)/Rtt_TextObject.o \
	$(OBJDIR)/Rtt_TextureFactory.o \
	$(OBJDIR)/Rtt_TextureResource.o \
	$(OBJDIR)/Rtt_TextureResourceAdapter.o \
	$(OBJDIR)/Rtt_TextureResourceBitmap.o \
	$(OBJDIR)/Rtt_TextureResourceBitmapAdapter.o \
	$(OBJDIR)/Rtt_TextureResourceCanvas.o \
	$(OBJDIR)/Rtt_TextureResourceCanvasAdapter.o \
	$(OBJDIR)/Rtt_TextureResourceExternal.o \
	$(OBJDIR)/Rtt_TextureResourceExternalAdapter.o \
	$(OBJDIR)/Rtt_VertexCache.o \
	$(OBJDIR)/Rtt_InputAxisCollection.o \
	$(OBJDIR)/Rtt_InputAxisDescriptor.o \
	$(OBJDIR)/Rtt_InputAxisType.o \
	$(OBJDIR)/Rtt_InputDeviceCollection.o \
	$(OBJDIR)/Rtt_InputDeviceConnectionState.o \
	$(OBJDIR)/Rtt_InputDeviceDescriptor.o \
	$(OBJDIR)/Rtt_InputDeviceType.o \
	$(OBJDIR)/Rtt_PlatformInputAxis.o \
	$(OBJDIR)/Rtt_PlatformInputDevice.o \
	$(OBJDIR)/Rtt_PlatformInputDeviceManager.o \
	$(OBJDIR)/Rtt_ReadOnlyInputAxisCollection.o \
	$(OBJDIR)/Rtt_ReadOnlyInputDeviceCollection.o \
	$(OBJDIR)/b2Separator.o \
	$(OBJDIR)/SmoothPolygon.o \
	$(OBJDIR)/composer.o \
	$(OBJDIR)/composer_scene.o \
	$(OBJDIR)/CoronaPrototype.o \
	$(OBJDIR)/CoronaProvider.o \
	$(OBJDIR)/easing.o \
	$(OBJDIR)/init.o \
	$(OBJDIR)/json.o \
	$(OBJDIR)/kernel_composite_add_gl.o \
	$(OBJDIR)/kernel_composite_average_gl.o \
	$(OBJDIR)/kernel_composite_color_gl.o \
	$(OBJDIR)/kernel_composite_colorBurn_gl.o \
	$(OBJDIR)/kernel_composite_colorDodge_gl.o \
	$(OBJDIR)/kernel_composite_darken_gl.o \
	$(OBJDIR)/kernel_composite_difference_gl.o \
	$(OBJDIR)/kernel_composite_exclusion_gl.o \
	$(OBJDIR)/kernel_composite_glow_gl.o \
	$(OBJDIR)/kernel_composite_hardLight_gl.o \
	$(OBJDIR)/kernel_composite_hardMix_gl.o \
	$(OBJDIR)/kernel_composite_hue_gl.o \
	$(OBJDIR)/kernel_composite_lighten_gl.o \
	$(OBJDIR)/kernel_composite_linearLight_gl.o \
	$(OBJDIR)/kernel_composite_luminosity_gl.o \
	$(OBJDIR)/kernel_composite_multiply_gl.o \
	$(OBJDIR)/kernel_composite_negation_gl.o \
	$(OBJDIR)/kernel_composite_normalMapWith1DirLight_gl.o \
	$(OBJDIR)/kernel_composite_normalMapWith1PointLight_gl.o \
	$(OBJDIR)/kernel_composite_overlay_gl.o \
	$(OBJDIR)/kernel_composite_phoenix_gl.o \
	$(OBJDIR)/kernel_composite_pinLight_gl.o \
	$(OBJDIR)/kernel_composite_reflect_gl.o \
	$(OBJDIR)/kernel_composite_saturation_gl.o \
	$(OBJDIR)/kernel_composite_screen_gl.o \
	$(OBJDIR)/kernel_composite_softLight_gl.o \
	$(OBJDIR)/kernel_composite_subtract_gl.o \
	$(OBJDIR)/kernel_composite_vividLight_gl.o \
	$(OBJDIR)/kernel_composite_yuv420f_gl.o \
	$(OBJDIR)/kernel_default_gl.o \
	$(OBJDIR)/kernel_filter_bloom_gl.o \
	$(OBJDIR)/kernel_filter_blur_gl.o \
	$(OBJDIR)/kernel_filter_blurGaussian_gl.o \
	$(OBJDIR)/kernel_filter_blurLinearVertical_gl.o \
	$(OBJDIR)/kernel_filter_blurLinearHorizontal_gl.o \
	$(OBJDIR)/kernel_filter_blurGaussianLinear_gl.o \
	$(OBJDIR)/kernel_filter_blurHorizontal_gl.o \
	$(OBJDIR)/kernel_filter_blurVertical_gl.o \
	$(OBJDIR)/kernel_filter_brightness_gl.o \
	$(OBJDIR)/kernel_filter_bulge_gl.o \
	$(OBJDIR)/kernel_filter_chromaKey_gl.o \
	$(OBJDIR)/kernel_filter_color_gl.o \
	$(OBJDIR)/kernel_filter_colorChannelOffset_gl.o \
	$(OBJDIR)/kernel_filter_colorMatrix_gl.o \
	$(OBJDIR)/kernel_filter_colorPolynomial_gl.o \
	$(OBJDIR)/kernel_filter_contrast_gl.o \
	$(OBJDIR)/kernel_filter_crosshatch_gl.o \
	$(OBJDIR)/kernel_filter_crystallize_gl.o \
	$(OBJDIR)/kernel_filter_desaturate_gl.o \
	$(OBJDIR)/kernel_filter_dissolve_gl.o \
	$(OBJDIR)/kernel_filter_duotone_gl.o \
	$(OBJDIR)/kernel_filter_emboss_gl.o \
	$(OBJDIR)/kernel_filter_exposure_gl.o \
	$(OBJDIR)/kernel_filter_frostedGlass_gl.o \
	$(OBJDIR)/kernel_filter_grayscale_gl.o \
	$(OBJDIR)/kernel_filter_hue_gl.o \
	$(OBJDIR)/kernel_filter_invert_gl.o \
	$(OBJDIR)/kernel_filter_iris_gl.o \
	$(OBJDIR)/kernel_filter_levels_gl.o \
	$(OBJDIR)/kernel_filter_linearWipe_gl.o \
	$(OBJDIR)/kernel_filter_median_gl.o \
	$(OBJDIR)/kernel_filter_monotone_gl.o \
	$(OBJDIR)/kernel_filter_opTile_gl.o \
	$(OBJDIR)/kernel_filter_pixelate_gl.o \
	$(OBJDIR)/kernel_filter_polkaDots_gl.o \
	$(OBJDIR)/kernel_filter_posterize_gl.o \
	$(OBJDIR)/kernel_filter_radialWipe_gl.o \
	$(OBJDIR)/kernel_filter_saturate_gl.o \
	$(OBJDIR)/kernel_filter_scatter_gl.o \
	$(OBJDIR)/kernel_filter_sepia_gl.o \
	$(OBJDIR)/kernel_filter_sharpenLuminance_gl.o \
	$(OBJDIR)/kernel_filter_sobel_gl.o \
	$(OBJDIR)/kernel_filter_straighten_gl.o \
	$(OBJDIR)/kernel_filter_swirl_gl.o \
	$(OBJDIR)/kernel_filter_vignette_gl.o \
	$(OBJDIR)/kernel_filter_vignetteMask_gl.o \
	$(OBJDIR)/kernel_filter_wobble_gl.o \
	$(OBJDIR)/kernel_filter_woodCut_gl.o \
	$(OBJDIR)/kernel_filter_zoomBlur_gl.o \
	$(OBJDIR)/kernel_generator_checkerboard_gl.o \
	$(OBJDIR)/kernel_generator_lenticularHalo_gl.o \
	$(OBJDIR)/kernel_generator_linearGradient_gl.o \
	$(OBJDIR)/kernel_generator_marchingAnts_gl.o \
	$(OBJDIR)/kernel_generator_perlinNoise_gl.o \
	$(OBJDIR)/kernel_generator_radialGradient_gl.o \
	$(OBJDIR)/kernel_generator_random_gl.o \
	$(OBJDIR)/kernel_generator_stripes_gl.o \
	$(OBJDIR)/kernel_generator_sunbeams_gl.o \
	$(OBJDIR)/re.o \
	$(OBJDIR)/runtime.o \
	$(OBJDIR)/shell.o \
	$(OBJDIR)/shell_default_gl.o \
	$(OBJDIR)/timer.o \
	$(OBJDIR)/transition.o \
	$(OBJDIR)/transition_v1.o \
	$(OBJDIR)/widget.o \
	$(OBJDIR)/widget_button.o \
	$(OBJDIR)/widget_momentumScrolling.o \
	$(OBJDIR)/widget_pickerWheel.o \
	$(OBJDIR)/widget_progressView.o \
	$(OBJDIR)/widget_scrollview.o \
	$(OBJDIR)/widget_searchField.o \
	$(OBJDIR)/widget_segmentedControl.o \
	$(OBJDIR)/widget_slider.o \
	$(OBJDIR)/widget_spinner.o \
	$(OBJDIR)/widget_stepper.o \
	$(OBJDIR)/widget_switch.o \
	$(OBJDIR)/widget_tabbar.o \
	$(OBJDIR)/widget_tableview.o \
	$(OBJDIR)/widget_theme_android.o \
	$(OBJDIR)/widget_theme_android_sheet.o \
	$(OBJDIR)/widget_theme_android_holo_dark.o \
	$(OBJDIR)/widget_theme_android_holo_dark_sheet.o \
	$(OBJDIR)/widget_theme_android_holo_light.o \
	$(OBJDIR)/widget_theme_android_holo_light_sheet.o \
	$(OBJDIR)/widget_theme_ios.o \
	$(OBJDIR)/widget_theme_ios7.o \
	$(OBJDIR)/widget_theme_ios7_sheet.o \
	$(OBJDIR)/widget_theme_ios_sheet.o \
	$(OBJDIR)/kernel_filter_water_gl.o \
	$(OBJDIR)/kernel_filter_step_gl.o \
	$(OBJDIR)/dkjson.o \
	$(OBJDIR)/CoronaLibrary-lua.o \
	$(OBJDIR)/launchpad.o \
	$(OBJDIR)/loader_callback.o \
	$(OBJDIR)/loader_ccdata.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking rtt
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning rtt
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -MMD -MP $(DEFINES) $(INCLUDES) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/Rtt_Preference.o: ../../../librtt/Rtt_Preference.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PreferenceCollection.o: ../../../librtt/Rtt_PreferenceCollection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PreferenceValue.o: ../../../librtt/Rtt_PreferenceValue.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorMesh.o: ../../../librtt/Display/Rtt_TesselatorMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_OperationResult.o: ../../../librtt/Core/Rtt_OperationResult.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapeAdapterMesh.o: ../../../librtt/Display/Rtt_ShapeAdapterMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaCoronaBaseLib.o: ../../../librtt/Rtt_LuaCoronaBaseLib.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Assert.o: ../../../librtt/Core/Rtt_Assert.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Fixed.o: ../../../librtt/Core/Rtt_Fixed.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_FixedMath.o: ../../../librtt/Core/Rtt_FixedMath.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Math.o: ../../../librtt/Core/Rtt_Math.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Time.o: ../../../librtt/Core/Rtt_Time.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_VersionTimestamp.o: ../../../librtt/Core/Rtt_VersionTimestamp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaAssert.o: ../../../librtt/Corona/CoronaAssert.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaLog.o: ../../../librtt/Corona/CoronaLog.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaVersion.o: ../../../librtt/Corona/CoronaVersion.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2GLESDebugDraw.o: ../../../librtt/b2GLESDebugDraw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Archive.o: ../../../librtt/Rtt_Archive.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_CachedPath.o: ../../../librtt/Rtt_CachedPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_DeviceOrientation.o: ../../../librtt/Rtt_DeviceOrientation.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_DisplayObjectExtensions.o: ../../../librtt/Rtt_DisplayObjectExtensions.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Event.o: ../../../librtt/Rtt_Event.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ExplicitTemplates.o: ../../../librtt/Rtt_ExplicitTemplates.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_FilePath.o: ../../../librtt/Rtt_FilePath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_FillTesselatorStream.o: ../../../librtt/Rtt_FillTesselatorStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_GPUStream.o: ../../../librtt/Rtt_GPUStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_HitTestObject.o: ../../../librtt/Rtt_HitTestObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_KeyName.o: ../../../librtt/Rtt_KeyName.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Lua.o: ../../../librtt/Rtt_Lua.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaAssert.o: ../../../librtt/Rtt_LuaAssert.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaAux.o: ../../../librtt/Rtt_LuaAux.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaContainer.o: ../../../librtt/Rtt_LuaContainer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaContext.o: ../../../librtt/Rtt_LuaContext.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaData.o: ../../../librtt/Rtt_LuaData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibCrypto.o: ../../../librtt/Rtt_LuaLibCrypto.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibFacebook.o: ../../../librtt/Rtt_LuaLibFacebook.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibFlurry.o: ../../../librtt/Rtt_LuaLibFlurry.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibGameNetwork.o: ../../../librtt/Rtt_LuaLibGameNetwork.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibInAppStore.o: ../../../librtt/Rtt_LuaLibInAppStore.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibMedia.o: ../../../librtt/Rtt_LuaLibMedia.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibNative.o: ../../../librtt/Rtt_LuaLibNative.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibPhysics.o: ../../../librtt/Rtt_LuaLibPhysics.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibSQLite.o: ../../../librtt/Rtt_LuaLibSQLite.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibSystem.o: ../../../librtt/Rtt_LuaLibSystem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaProxy.o: ../../../librtt/Rtt_LuaProxy.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaProxyVTable.o: ../../../librtt/Rtt_LuaProxyVTable.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaResource.o: ../../../librtt/Rtt_LuaResource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaResourceOwner.o: ../../../librtt/Rtt_LuaResourceOwner.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaTableIterator.o: ../../../librtt/Rtt_LuaTableIterator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaUserdataProxy.o: ../../../librtt/Rtt_LuaUserdataProxy.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Matrix.o: ../../../librtt/Rtt_Matrix.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ParticleSystemObject.o: ../../../librtt/Rtt_ParticleSystemObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PhysicsContact.o: ../../../librtt/Rtt_PhysicsContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PhysicsContactListener.o: ../../../librtt/Rtt_PhysicsContactListener.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PhysicsJoint.o: ../../../librtt/Rtt_PhysicsJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PhysicsWorld.o: ../../../librtt/Rtt_PhysicsWorld.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformAudioPlayer.o: ../../../librtt/Rtt_PlatformAudioPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformAudioRecorder.o: ../../../librtt/Rtt_PlatformAudioRecorder.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformAudioSessionManager.o: ../../../librtt/Rtt_PlatformAudioSessionManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformData.o: ../../../librtt/Rtt_PlatformData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformDisplayObject.o: ../../../librtt/Rtt_PlatformDisplayObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformEventSound.o: ../../../librtt/Rtt_PlatformEventSound.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformExitCallback.o: ../../../librtt/Rtt_PlatformExitCallback.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformFBConnect.o: ../../../librtt/Rtt_PlatformFBConnect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformFont.o: ../../../librtt/Rtt_PlatformFont.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformImageProvider.o: ../../../librtt/Rtt_PlatformImageProvider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformInAppStore.o: ../../../librtt/Rtt_PlatformInAppStore.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformLocation.o: ../../../librtt/Rtt_PlatformLocation.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformModalInteraction.o: ../../../librtt/Rtt_PlatformModalInteraction.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformNotifier.o: ../../../librtt/Rtt_PlatformNotifier.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformReachability.o: ../../../librtt/Rtt_PlatformReachability.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformSurface.o: ../../../librtt/Rtt_PlatformSurface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformTimer.o: ../../../librtt/Rtt_PlatformTimer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformVideoPlayer.o: ../../../librtt/Rtt_PlatformVideoPlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformVideoProvider.o: ../../../librtt/Rtt_PlatformVideoProvider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformWebPopup.o: ../../../librtt/Rtt_PlatformWebPopup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Profiling.o: ../../../librtt/Rtt_Profiling.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_RenderingStream.o: ../../../librtt/Rtt_RenderingStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Resource.o: ../../../librtt/Rtt_Resource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Runtime.o: ../../../librtt/Rtt_Runtime.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_RuntimeDelegate.o: ../../../librtt/Rtt_RuntimeDelegate.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Scheduler.o: ../../../librtt/Rtt_Scheduler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_SimpleCachedPath.o: ../../../librtt/Rtt_SimpleCachedPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_StrokeTesselatorStream.o: ../../../librtt/Rtt_StrokeTesselatorStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorStream.o: ../../../librtt/Rtt_TesselatorStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Transform.o: ../../../librtt/Rtt_Transform.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Allocator.o: ../../../librtt/Core/Rtt_Allocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Array.o: ../../../librtt/Core/Rtt_Array.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ArrayTuple.o: ../../../librtt/Core/Rtt_ArrayTuple.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ArrayTupleStruct.o: ../../../librtt/Core/Rtt_ArrayTupleStruct.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_AutoResource.o: ../../../librtt/Core/Rtt_AutoResource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_FileSystem.o: ../../../librtt/Core/Rtt_FileSystem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_FixedBlockAllocator.o: ../../../librtt/Core/Rtt_FixedBlockAllocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Geometry.o: ../../../librtt/Core/Rtt_Geometry.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_RefCount.o: ../../../librtt/Core/Rtt_RefCount.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ResourceHandle.o: ../../../librtt/Core/Rtt_ResourceHandle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_SharedCount.o: ../../../librtt/Core/Rtt_SharedCount.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_String.o: ../../../librtt/Core/Rtt_String.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_StringHash.o: ../../../librtt/Core/Rtt_StringHash.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_UseCount.o: ../../../librtt/Core/Rtt_UseCount.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_WeakCount.o: ../../../librtt/Core/Rtt_WeakCount.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaEvent.o: ../../../librtt/Corona/CoronaEvent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaLibrary.o: ../../../librtt/Corona/CoronaLibrary.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaLua.o: ../../../librtt/Corona/CoronaLua.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaMemory.o: ../../../librtt/Corona/CoronaMemory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_BitmapMask.o: ../../../librtt/Display/Rtt_BitmapMask.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_BitmapPaint.o: ../../../librtt/Display/Rtt_BitmapPaint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_BitmapPaintAdapter.o: ../../../librtt/Display/Rtt_BitmapPaintAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ImageSheetPaintAdapter.o: ../../../librtt/Display/Rtt_ImageSheetPaintAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_BufferBitmap.o: ../../../librtt/Display/Rtt_BufferBitmap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_CameraPaint.o: ../../../librtt/Display/Rtt_CameraPaint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ClosedPath.o: ../../../librtt/Display/Rtt_ClosedPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_CompositeObject.o: ../../../librtt/Display/Rtt_CompositeObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_CompositePaint.o: ../../../librtt/Display/Rtt_CompositePaint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ContainerObject.o: ../../../librtt/Display/Rtt_ContainerObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_CPUResourcePool.o: ../../../librtt/Display/Rtt_CPUResourcePool.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Display.o: ../../../librtt/Display/Rtt_Display.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_DisplayDefaults.o: ../../../librtt/Display/Rtt_DisplayDefaults.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_DisplayObject.o: ../../../librtt/Display/Rtt_DisplayObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_DisplayPath.o: ../../../librtt/Display/Rtt_DisplayPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmbossedTextObject.o: ../../../librtt/Display/Rtt_EmbossedTextObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_EmitterObject.o: ../../../librtt/Display/Rtt_EmitterObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_GradientPaint.o: ../../../librtt/Display/Rtt_GradientPaint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_GradientPaintAdapter.o: ../../../librtt/Display/Rtt_GradientPaintAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_GroupObject.o: ../../../librtt/Display/Rtt_GroupObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ImageFrame.o: ../../../librtt/Display/Rtt_ImageFrame.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ImageSheet.o: ../../../librtt/Display/Rtt_ImageSheet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ImageSheetPaint.o: ../../../librtt/Display/Rtt_ImageSheetPaint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ImageSheetUserdata.o: ../../../librtt/Display/Rtt_ImageSheetUserdata.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LineObject.o: ../../../librtt/Display/Rtt_LineObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibDisplay.o: ../../../librtt/Display/Rtt_LuaLibDisplay.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_LuaLibGraphics.o: ../../../librtt/Display/Rtt_LuaLibGraphics.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_OpenPath.o: ../../../librtt/Display/Rtt_OpenPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Paint.o: ../../../librtt/Display/Rtt_Paint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PaintAdapter.o: ../../../librtt/Display/Rtt_PaintAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformBitmap.o: ../../../librtt/Display/Rtt_PlatformBitmap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformBitmapTexture.o: ../../../librtt/Display/Rtt_PlatformBitmapTexture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_RectObject.o: ../../../librtt/Display/Rtt_RectObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_RectPath.o: ../../../librtt/Display/Rtt_RectPath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Scene.o: ../../../librtt/Display/Rtt_Scene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Shader.o: ../../../librtt/Display/Rtt_Shader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderBuiltin.o: ../../../librtt/Display/Rtt_ShaderBuiltin.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderCache.o: ../../../librtt/Display/Rtt_ShaderCache.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderComposite.o: ../../../librtt/Display/Rtt_ShaderComposite.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderCompositeAdapter.o: ../../../librtt/Display/Rtt_ShaderCompositeAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderData.o: ../../../librtt/Display/Rtt_ShaderData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderDataAdapter.o: ../../../librtt/Display/Rtt_ShaderDataAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderFactory.o: ../../../librtt/Display/Rtt_ShaderFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderInput.o: ../../../librtt/Display/Rtt_ShaderInput.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderName.o: ../../../librtt/Display/Rtt_ShaderName.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderProxy.o: ../../../librtt/Display/Rtt_ShaderProxy.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderResource.o: ../../../librtt/Display/Rtt_ShaderResource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShaderTypes.o: ../../../librtt/Display/Rtt_ShaderTypes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapeAdapter.o: ../../../librtt/Display/Rtt_ShapeAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapeAdapterCircle.o: ../../../librtt/Display/Rtt_ShapeAdapterCircle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapeAdapterPolygon.o: ../../../librtt/Display/Rtt_ShapeAdapterPolygon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapeAdapterRect.o: ../../../librtt/Display/Rtt_ShapeAdapterRect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapeAdapterRoundedRect.o: ../../../librtt/Display/Rtt_ShapeAdapterRoundedRect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapeObject.o: ../../../librtt/Display/Rtt_ShapeObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ShapePath.o: ../../../librtt/Display/Rtt_ShapePath.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_SnapshotObject.o: ../../../librtt/Display/Rtt_SnapshotObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_SpriteObject.o: ../../../librtt/Display/Rtt_SpriteObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_SpritePlayer.o: ../../../librtt/Display/Rtt_SpritePlayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_SpriteSourceFrame.o: ../../../librtt/Display/Rtt_SpriteSourceFrame.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_StageObject.o: ../../../librtt/Display/Rtt_StageObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_Tesselator.o: ../../../librtt/Display/Rtt_Tesselator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorCircle.o: ../../../librtt/Display/Rtt_TesselatorCircle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorLine.o: ../../../librtt/Display/Rtt_TesselatorLine.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorPolygon.o: ../../../librtt/Display/Rtt_TesselatorPolygon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorRect.o: ../../../librtt/Display/Rtt_TesselatorRect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorRoundedRect.o: ../../../librtt/Display/Rtt_TesselatorRoundedRect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TesselatorShape.o: ../../../librtt/Display/Rtt_TesselatorShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextObject.o: ../../../librtt/Display/Rtt_TextObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureFactory.o: ../../../librtt/Display/Rtt_TextureFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResource.o: ../../../librtt/Display/Rtt_TextureResource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResourceAdapter.o: ../../../librtt/Display/Rtt_TextureResourceAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResourceBitmap.o: ../../../librtt/Display/Rtt_TextureResourceBitmap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResourceBitmapAdapter.o: ../../../librtt/Display/Rtt_TextureResourceBitmapAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResourceCanvas.o: ../../../librtt/Display/Rtt_TextureResourceCanvas.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResourceCanvasAdapter.o: ../../../librtt/Display/Rtt_TextureResourceCanvasAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResourceExternal.o: ../../../librtt/Display/Rtt_TextureResourceExternal.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_TextureResourceExternalAdapter.o: ../../../librtt/Display/Rtt_TextureResourceExternalAdapter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_VertexCache.o: ../../../librtt/Display/Rtt_VertexCache.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_InputAxisCollection.o: ../../../librtt/Input/Rtt_InputAxisCollection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_InputAxisDescriptor.o: ../../../librtt/Input/Rtt_InputAxisDescriptor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_InputAxisType.o: ../../../librtt/Input/Rtt_InputAxisType.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_InputDeviceCollection.o: ../../../librtt/Input/Rtt_InputDeviceCollection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_InputDeviceConnectionState.o: ../../../librtt/Input/Rtt_InputDeviceConnectionState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_InputDeviceDescriptor.o: ../../../librtt/Input/Rtt_InputDeviceDescriptor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_InputDeviceType.o: ../../../librtt/Input/Rtt_InputDeviceType.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformInputAxis.o: ../../../librtt/Input/Rtt_PlatformInputAxis.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformInputDevice.o: ../../../librtt/Input/Rtt_PlatformInputDevice.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_PlatformInputDeviceManager.o: ../../../librtt/Input/Rtt_PlatformInputDeviceManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ReadOnlyInputAxisCollection.o: ../../../librtt/Input/Rtt_ReadOnlyInputAxisCollection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/Rtt_ReadOnlyInputDeviceCollection.o: ../../../librtt/Input/Rtt_ReadOnlyInputDeviceCollection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/b2Separator.o: ../../../external/b2Separator-cpp/b2Separator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/SmoothPolygon.o: ../../../external/smoothpolygon/SmoothPolygon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/composer.o: ../lua/composer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/composer_scene.o: ../lua/composer_scene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaPrototype.o: ../lua/CoronaPrototype.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaProvider.o: ../lua/CoronaProvider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/easing.o: ../lua/easing.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/init.o: ../lua/init.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/json.o: ../lua/json.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_add_gl.o: ../lua/kernel_composite_add_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_average_gl.o: ../lua/kernel_composite_average_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_color_gl.o: ../lua/kernel_composite_color_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_colorBurn_gl.o: ../lua/kernel_composite_colorBurn_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_colorDodge_gl.o: ../lua/kernel_composite_colorDodge_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_darken_gl.o: ../lua/kernel_composite_darken_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_difference_gl.o: ../lua/kernel_composite_difference_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_exclusion_gl.o: ../lua/kernel_composite_exclusion_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_glow_gl.o: ../lua/kernel_composite_glow_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_hardLight_gl.o: ../lua/kernel_composite_hardLight_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_hardMix_gl.o: ../lua/kernel_composite_hardMix_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_hue_gl.o: ../lua/kernel_composite_hue_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_lighten_gl.o: ../lua/kernel_composite_lighten_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_linearLight_gl.o: ../lua/kernel_composite_linearLight_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_luminosity_gl.o: ../lua/kernel_composite_luminosity_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_multiply_gl.o: ../lua/kernel_composite_multiply_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_negation_gl.o: ../lua/kernel_composite_negation_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_normalMapWith1DirLight_gl.o: ../lua/kernel_composite_normalMapWith1DirLight_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_normalMapWith1PointLight_gl.o: ../lua/kernel_composite_normalMapWith1PointLight_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_overlay_gl.o: ../lua/kernel_composite_overlay_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_phoenix_gl.o: ../lua/kernel_composite_phoenix_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_pinLight_gl.o: ../lua/kernel_composite_pinLight_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_reflect_gl.o: ../lua/kernel_composite_reflect_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_saturation_gl.o: ../lua/kernel_composite_saturation_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_screen_gl.o: ../lua/kernel_composite_screen_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_softLight_gl.o: ../lua/kernel_composite_softLight_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_subtract_gl.o: ../lua/kernel_composite_subtract_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_vividLight_gl.o: ../lua/kernel_composite_vividLight_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_composite_yuv420f_gl.o: ../lua/kernel_composite_yuv420f_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_default_gl.o: ../lua/kernel_default_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_bloom_gl.o: ../lua/kernel_filter_bloom_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_blur_gl.o: ../lua/kernel_filter_blur_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_blurGaussian_gl.o: ../lua/kernel_filter_blurGaussian_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_blurLinearVertical_gl.o: ../lua/kernel_filter_blurLinearVertical_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_blurLinearHorizontal_gl.o: ../lua/kernel_filter_blurLinearHorizontal_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_blurGaussianLinear_gl.o: ../lua/kernel_filter_blurGaussianLinear_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_blurHorizontal_gl.o: ../lua/kernel_filter_blurHorizontal_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_blurVertical_gl.o: ../lua/kernel_filter_blurVertical_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_brightness_gl.o: ../lua/kernel_filter_brightness_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_bulge_gl.o: ../lua/kernel_filter_bulge_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_chromaKey_gl.o: ../lua/kernel_filter_chromaKey_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_color_gl.o: ../lua/kernel_filter_color_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_colorChannelOffset_gl.o: ../lua/kernel_filter_colorChannelOffset_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_colorMatrix_gl.o: ../lua/kernel_filter_colorMatrix_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_colorPolynomial_gl.o: ../lua/kernel_filter_colorPolynomial_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_contrast_gl.o: ../lua/kernel_filter_contrast_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_crosshatch_gl.o: ../lua/kernel_filter_crosshatch_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_crystallize_gl.o: ../lua/kernel_filter_crystallize_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_desaturate_gl.o: ../lua/kernel_filter_desaturate_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_dissolve_gl.o: ../lua/kernel_filter_dissolve_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_duotone_gl.o: ../lua/kernel_filter_duotone_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_emboss_gl.o: ../lua/kernel_filter_emboss_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_exposure_gl.o: ../lua/kernel_filter_exposure_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_frostedGlass_gl.o: ../lua/kernel_filter_frostedGlass_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_grayscale_gl.o: ../lua/kernel_filter_grayscale_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_hue_gl.o: ../lua/kernel_filter_hue_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_invert_gl.o: ../lua/kernel_filter_invert_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_iris_gl.o: ../lua/kernel_filter_iris_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_levels_gl.o: ../lua/kernel_filter_levels_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_linearWipe_gl.o: ../lua/kernel_filter_linearWipe_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_median_gl.o: ../lua/kernel_filter_median_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_monotone_gl.o: ../lua/kernel_filter_monotone_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_opTile_gl.o: ../lua/kernel_filter_opTile_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_pixelate_gl.o: ../lua/kernel_filter_pixelate_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_polkaDots_gl.o: ../lua/kernel_filter_polkaDots_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_posterize_gl.o: ../lua/kernel_filter_posterize_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_radialWipe_gl.o: ../lua/kernel_filter_radialWipe_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_saturate_gl.o: ../lua/kernel_filter_saturate_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_scatter_gl.o: ../lua/kernel_filter_scatter_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_sepia_gl.o: ../lua/kernel_filter_sepia_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_sharpenLuminance_gl.o: ../lua/kernel_filter_sharpenLuminance_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_sobel_gl.o: ../lua/kernel_filter_sobel_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_straighten_gl.o: ../lua/kernel_filter_straighten_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_swirl_gl.o: ../lua/kernel_filter_swirl_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_vignette_gl.o: ../lua/kernel_filter_vignette_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_vignetteMask_gl.o: ../lua/kernel_filter_vignetteMask_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_wobble_gl.o: ../lua/kernel_filter_wobble_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_woodCut_gl.o: ../lua/kernel_filter_woodCut_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_zoomBlur_gl.o: ../lua/kernel_filter_zoomBlur_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_checkerboard_gl.o: ../lua/kernel_generator_checkerboard_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_lenticularHalo_gl.o: ../lua/kernel_generator_lenticularHalo_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_linearGradient_gl.o: ../lua/kernel_generator_linearGradient_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_marchingAnts_gl.o: ../lua/kernel_generator_marchingAnts_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_perlinNoise_gl.o: ../lua/kernel_generator_perlinNoise_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_radialGradient_gl.o: ../lua/kernel_generator_radialGradient_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_random_gl.o: ../lua/kernel_generator_random_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_stripes_gl.o: ../lua/kernel_generator_stripes_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_generator_sunbeams_gl.o: ../lua/kernel_generator_sunbeams_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/re.o: ../lua/re.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/runtime.o: ../lua/runtime.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/shell.o: ../lua/shell.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/shell_default_gl.o: ../lua/shell_default_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/timer.o: ../lua/timer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/transition.o: ../lua/transition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/transition_v1.o: ../lua/transition_v1.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget.o: ../lua/widget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_button.o: ../lua/widget_button.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_momentumScrolling.o: ../lua/widget_momentumScrolling.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_pickerWheel.o: ../lua/widget_pickerWheel.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_progressView.o: ../lua/widget_progressView.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_scrollview.o: ../lua/widget_scrollview.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_searchField.o: ../lua/widget_searchField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_segmentedControl.o: ../lua/widget_segmentedControl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_slider.o: ../lua/widget_slider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_spinner.o: ../lua/widget_spinner.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_stepper.o: ../lua/widget_stepper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_switch.o: ../lua/widget_switch.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_tabbar.o: ../lua/widget_tabbar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_tableview.o: ../lua/widget_tableview.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_android.o: ../lua/widget_theme_android.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_android_sheet.o: ../lua/widget_theme_android_sheet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_android_holo_dark.o: ../lua/widget_theme_android_holo_dark.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_android_holo_dark_sheet.o: ../lua/widget_theme_android_holo_dark_sheet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_android_holo_light.o: ../lua/widget_theme_android_holo_light.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_android_holo_light_sheet.o: ../lua/widget_theme_android_holo_light_sheet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_ios.o: ../lua/widget_theme_ios.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_ios7.o: ../lua/widget_theme_ios7.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_ios7_sheet.o: ../lua/widget_theme_ios7_sheet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/widget_theme_ios_sheet.o: ../lua/widget_theme_ios_sheet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/CoronaLibrary-lua.o: ../lua/CoronaLibrary.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/launchpad.o: ../lua/launchpad.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/loader_callback.o: ../lua/loader_callback.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/loader_ccdata.o: ../lua/loader_ccdata.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_water_gl.o: ../lua/kernel_filter_water_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/kernel_filter_step_gl.o: ../lua/kernel_filter_step_gl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

$(OBJDIR)/dkjson.o: ../lua/dkjson.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif
