name: solar2d
title: Solar2D
#contact: https://github.com/coronalabs/corona/issues/
#donation: https://github.com/coronalabs/corona?sponsor=1
#issues: https://github.com/coronalabs/corona/issues/
#source-code: https://github.com/coronalabs/corona/
#website: https://solar2d.com/
license: MIT
icon: snap/gui/solar2d.svg
base: core20
version: '2100.9999'
summary: Solar2D Game Engine
description: Solar2D is a Lua based game engine with focus on ease of iterations and usage
grade: stable
confinement: classic
architectures:
  - amd64

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.solar2d.simulator


apps:
  solar2d:
    command: bin/desktop-launch $SNAP/usr/local/bin/Solar2D/Solar2DSimulator
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/local/lib
    plugs:
      - desktop
      - opengl
      - network
      - network-bind 
      - camera
      - alsa
      - audio-playback
      - audio-record
      - gsettings
      - home
    slots:
      - dbus-daemon

  builder:
    command: usr/local/bin/Solar2D/Solar2DBuilder
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/local/lib
    plugs:
      - network
      - network-bind 

parts:
  readline:
    source: http://mirrors.kernel.org/ubuntu/pool/main/r/readline/libreadline7_7.0-3_amd64.deb
    plugin: dump
    source-type: deb

  wxwidgets:
    plugin: autotools
    source: https://github.com/coronalabs/binary-data/releases/download/1.0/wxWidgets-3.1.4.tar.bz2
    autotools-configure-parameters:
      - --with-gtk
      - --with-opengl
    after:
      - readline
    build-packages:
      - libcrypto++-dev
      - libcurl4-openssl-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libssl-dev
      - libvorbis-dev
      - libwebkit2gtk-4.0-dev
      - uuid-dev
      - zlib1g-dev
      - libcanberra-gtk3-dev
      - libcanberra-gtk3-module
      - libtiff5-dev
      - liblzma-dev
      
    stage-packages:
      - libcrypto++6
      - libcurl4
      - libfreetype6
      - libgl1
      - libglu1-mesa
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libjpeg8
      - libogg0
      - libopenal1
      - libpng16-16
      - libssl1.1
      - libvorbis0a
      - libwebkit2gtk-4.0-37
      - libuuid1
      - zlib1g
      - libice6
      - libsm6
      - libxtst6
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libtiff5
      - liblzma5

  desktop-helper:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5

  solar2d:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_LIBRARY_PATH=$SNAPCRAFT_STAGE/usr/local/lib
      - -DCMAKE_INCLUDE_PATH=$SNAPCRAFT_STAGE/usr/local/include
      - -DSNAPCRAFT_STAGE=${SNAPCRAFT_STAGE}
    after:
      - wxwidgets
      - desktop-helper
    override-build: |
      snapcraftctl build
      chmod -c -R a+r .      
    build-packages:
      - libcrypto++-dev
      - libcurl4-openssl-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libssl-dev
      - libvorbis-dev
      - libwebkit2gtk-4.0-dev
      - uuid-dev
      - zlib1g-dev
      - libcanberra-gtk3-dev
      - libcanberra-gtk3-module
      - libtiff5-dev
      - liblzma-dev
      - dos2unix
    stage-packages:
      - libcrypto++6
      - libcurl4
      - libfreetype6
      - libgl1
      - libglu1-mesa
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libjpeg8
      - libogg0
      - libopenal1
      - libpng16-16
      - libssl1.1
      - libvorbis0a
      - libwebkit2gtk-4.0-37
      - libuuid1
      - zlib1g
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libtiff5
      - liblzma5
      - gsettings-desktop-schemas
