name: Remove old artifacts

on:
  repository_dispatch:
    types:
      - purge
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: ${{ github.event.client_payload.age || '1 week' }}
        skip-tags: false