name: Test build

on:
  push:


env:
  WORKSPACE: ${{ github.workspace }}
  DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

jobs:

  Windows-Simulator:
    runs-on: windows-latest
    steps:
      - name: Before
        shell: cmd
        run: |
          mkdir logs
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" export --channelId VisualStudio.16.Release --productId Microsoft.VisualStudio.Product.Enterprise --config logs\before.txt -q
      - name: Add Packages
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --channelId VisualStudio.16.Release --productId Microsoft.VisualStudio.Product.Enterprise -q --includeRecommended --add "Microsoft.VisualStudio.Component.VC.ATL" --add "Microsoft.VisualStudio.Component.VC.ATLMFC" --add "Microsoft.VisualStudio.Component.VC.v141.x86.x64" --add "Microsoft.VisualStudio.Component.VC.140" --add "Microsoft.VisualStudio.Component.WinXP" --add "Microsoft.VisualStudio.Component.VC.v141.ATL" --add "Microsoft.VisualStudio.Component.VC.v141.MFC"
      - name: After
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" export --channelId VisualStudio.16.Release --productId Microsoft.VisualStudio.Product.Enterprise --config logs\after.txt -q
      - uses: actions/upload-artifact@v2
        if: true
        with:
          name: logsBA
          path: logs
